### ISSUE TITLE
No image after running：bash launch_evaluation.bash 1 vision

### ISSUE THREAD

**Issue by yifeichen2024** [anish-bhattacharya/ViT-for-quadrotor-obstacle-avoidance#2]
Hi, thank you for giving this creative and interesting work. 
When I run the` testbash launch_evaluation.bash 1 vision`,  I did not see any errors but there was no image in gazebo and the  flightmare simulation.  Is this the right output? 
Also I am very interested in the real-world deployment of this project. I saw your experiments in a relative simple indoor settings, did you try some more complex environment? like the forest and envs just like the flightmare simulations.
Thank you again for this great work!

**Comment by anish-bhattacharya** [comment]
Re: no image, if you look at RVIZ or at another viewer like `rqt_image_view`, you should get a depth image stream on the topic `/kingfisher/dodgeros_pilot/unity/depth`. If you don't, it could be due to some graphics issue on the Unity side -- I would recommend looking at the issues on [the original Flightmare repo](https://github.com/uzh-rpg/flightmare) and [the original ICRA 2022 dodgedrone competition repo](https://github.com/uzh-rpg/agile_flight). These repos will have lots of information and debugging tips in the issues. By the way, if you mean that you don't see the _environment_ in the Unity window pop-up then that would also indicate a graphics issue.

No, as of yet we have not deployed in a more complex real-world environment for safety reasons, but we are confident it will work well and aim to attempt this very soon!

**Comment by yifeichen2024** [comment]
Thanks! It's good to know!
