### ISSUE TITLE
Bridge failed!

### ISSUE THREAD

**Issue by giangdao1402** [anish-bhattacharya/ViT-for-quadrotor-obstacle-avoidance#3]
I have tested your package and this error occured
![Screenshot from 2024-10-12 15-54-35](https://github.com/user-attachments/assets/617c0f3f-ca2b-402d-bf94-9edb2c65efb6)

Have you ever encountered this error ?
BTW, Rviz still shows the image !

**Comment by anish-bhattacharya** [comment]
Unfortunately this might happen for multiple reasons, in my experience. [Some others online](https://github.com/uzh-rpg/agile_flight/issues/26) found they couldn't run it in a VM otherwise this would occur (though they specifically had a pyqt error msg). Other reasons may be package version mismatch from the original [DodgeDrone repo](https://github.com/uzh-rpg/agile_flight) requirements. I would recommend trying to install locally in a native Ubuntu environment and trying again.

Also the Bridge is the link between Unity and the envsim code. Does the Unity window pop up at all? Does it just show the welcome screen?

**Comment by giangdao1402** [comment]
Hi, I’m using a local Ubuntu setup, but it still isn’t working. I have successfully installed it on another PC. Thanks for your great work!
